### ISSUE TITLE
Only one backup per day?

### ISSUE THREAD

**Issue by pcav** [ewxrjk/rsbackup#49]
Unsure whether this is a bug or a feature: when running rsbackup multiple times in the same day, it seems to skip further backups (i.e. making only the first backup for a specific date).
In our case, it would be desirable to check at every run whether there are new or modified files. Failing to do so may result in data loss.
Is there an option for this?
Thanks.

**Comment by pcav** [comment]
Even if configs change (e.g. excluding new elements), the backup does not seem to be repeated in the same day.

**Comment by ewxrjk** [comment]
Indeed, there is a limit of one backup per day. This could be changed, with a bit of care to handle existing systems gracefully. It would have an impact on space used, since although identical files can be hardlinked within backups, the same is not true of identical directories. I'll have a think about the best way to approach it.

**Comment by pcav** [comment]
Thanks for clarifying. In our scripts, whch worked similar to rsb, we used a full timestamp as name of top dirs, instead of the date only.

**Comment by pcav** [comment]
Thanks
