### ISSUE TITLE
rsbackup-snapshot-hook fails to understand /dev/mapper/ming-home

### ISSUE THREAD

**Issue by MatthewVernon** [ewxrjk/rsbackup#72]
Hi,

I tried to turn on snapshots; config fragment:
```
host ming
  hostname localhost
  pre-backup-hook rsbackup-snapshot-hook
  post-backup-hook rsbackup-snapshot-hook
  prune-parameter prune-age 60
  volume root /
    exclude /srv/chroots/*
  volume home /home
    exclude /*/.mozilla/*/Cache/*
    exclude /*/.mozilla/*/*/Cache/*
```
[the change was adding the two hook lines]

This fails thus:
```
HOOK: EXEC: udevadm info -rqsymlink -n /dev/mapper/ming-home
ERROR: cannot parse device name /dev/mapper/ming-home
HOOK: EXEC: udevadm info -rqsymlink -n /dev/mapper/ming-home
ERROR: cannot parse device name /dev/mapper/ming-home
```

Similarly for root. Looking through rsbackup-snapshot-hook, you do:
```bash
  devname=$($remote df ${RSBACKUP_VOLUME_PATH}|awk '/^\// { print $1}')
  # Canonicalize the device name
  dev=""
  for alias in $(x $remote udevadm info -rqsymlink -n "$devname"); do
    case "$alias" in
    /dev/mapper/* )
      dev="${alias}"
      break
      ;;
    esac
  done
  if [ "${dev}" =  "" ]; then
    echo >&2 "ERROR: cannot parse device name $devname"
    exit 1
  fi
```
The first bit works OK, but the second returns an empty string:
```
matthew@aragorn:~$ df /home |awk '/^\// { print $1}'
/dev/mapper/ming-home
matthew@aragorn:~$ udevadm info -rqsymlink -n /dev/mapper/ming-home

matthew@aragorn:~$ echo $?
0
```
Maybe the snapshot hook should not try and canonicalise things that are already in `/dev/mapper`?

**Comment by ewxrjk** [comment]
`udevadm` copes perfectly well with names in `/dev/mapper` for me. I think something about udev must be broken on your system.

**Comment by MatthewVernon** [comment]
I don't think udev is broken here, maybe I just have an older version? `udevadm` does know about this device:
```
matthew@aragorn:~$ udevadm info /dev/mapper/ming-home
P: /devices/virtual/block/dm-2
N: dm-2
E: DEVNAME=/dev/dm-2
E: DEVPATH=/devices/virtual/block/dm-2
E: DEVTYPE=disk
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: MAJOR=253
E: MINOR=2
E: SUBSYSTEM=block
E: SYSTEMD_READY=0
E: TAGS=:systemd:
E: USEC_INITIALIZED=6586553

```
I have udev version 232-25+deb9u12 here

rsbackup-snapshot-hook could skip the udevadm step if `$devname` was already `/dev/mapper/*`, which would solve this?

**Comment by ewxrjk** [comment]
If udev is managing to create the symlink but doesn't then report that it did so then surely something is wrong with udev.

That looks like the udev from Debian stretch. But the code has been like that since 2015, i.e. well before stretch was released. So I don't believe the udevadm too old theory.

**Comment by jtn20** [comment]
I've run into the exact same issue: `udevadm info -rqsymlink` does not return any output for my LVs, so rsbackup-snapshot-hook refuses to work with them.
(What makes this particularly vexing is that my system does not suffer from the issue described in #23 which is why this `udevadm` invocation was introduced in the first place.)

This affects all LVs on a freshly installed Debian stable (bullseye) system, with LVM as set up by debian-installer, so I don't think it can be accused of being especially old or weird.
(For completeness, although I've no reason to think this is relevant: the installation does use sysvinit rather than systemd, and does not have merged /usr.)
I also have an oldstable (buster) system with a more complicated history/setup, where `udevadm` fails the same way on all but one of its LVs.

I suspect it might have something to do with whether the relevant LV is mounted early in boot, but I'm not especially interested in debugging udev. Instead, to continue to address #23, we can use `dmsetup` to get information about LVs instead of `udevadm`; it is closer to the source of truth, and so should be more reliable. I have prepared PR #109 to do this.

(I don't think I can reopen this issue myself, but I think this is the correct place to discuss this, and I'm hoping its status won't get in the way.)
